[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "make_this_importable"
version = "0.3.1"


[tool.setuptools]
packages = ["some_dir", "some_dir.another_dir"]